### ISSUE TITLE
Sourcemap is not properly exported in BitAuth URL for Mecenas contract

### ISSUE THREAD

**Issue by rkalis** [CashScript/cashscript#177]
<img width="980" alt="CleanShot 2023-12-20 at 12 59 25@2x" src="https://github.com/CashScript/cashscript/assets/9142187/6ad4315c-be32-43d8-b50d-c0ea26336aeb">

**Comment by rkalis** [comment]
Mathieu and I will look into this next week.

**Comment by mr-zwets** [comment]
I think we found the issue with this week's session as described in #172, the issue was the old fixtures not including debug information in the artifact.

The mecenas contract still has an issue, because it uses a comment in the middle of a cashscript line which causes a problem for the Bitauth IDE two way mapping.

This issue can either be closed now, or when the final issue with the mecenas source map is fixed.

**Comment by rkalis** [comment]
Today we also fixed the final remaining issue in the Mecenas contract.
